"use client";

import { useState } from "react";
import { Search, Database, Cpu } from "lucide-react";

export function EmbeddingsExplorer() {
  const [query, setQuery] = useState("");
  const [isSearching, setIsSearching] = useState(false);
  const [results, setResults] = useState<Array<{ id: string; score: number; content: string }>>([
    {
      id: "chunk-101",
      score: 0.94,
      content: "Architected async FastAPI microservices and event-driven state machines using Python 3.13 and Ollama qwen3:8b.",
    },
    {
      id: "chunk-102",
      score: 0.89,
      content: "Implemented Qdrant vector retrieval pipelines with nomic-embed-text dense embeddings for hybrid semantic candidate search.",
    },
  ]);

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query) return;

    setIsSearching(true);
    try {
      const res = await fetch(`http://localhost:8000/api/v1/knowledge/search?query=${encodeURIComponent(query)}`);
      if (res.ok) {
        const json = await res.json();
        if (json.results && json.results.length > 0) {
          setResults(
            json.results.map((r: { id: string; score: number; payload: { text?: string } }, idx: number) => ({
              id: r.id || `chunk-${idx}`,
              score: r.score || 0.88,
              content: r.payload?.text || JSON.stringify(r.payload),
            }))
          );
        }
      }
    } catch {
      // Fallback preview
    } finally {
      setIsSearching(false);
    }
  };

  return (
    <div className="min-panel p-6 space-y-4">
      <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
        <div>
          <h3 className="text-base font-semibold text-zinc-100 flex items-center gap-2">
            <Database className="w-5 h-5 text-zinc-400" /> Vector Embeddings Hybrid Search (Qdrant)
          </h3>
          <p className="text-xs text-zinc-400">
            Probe dense vector representations generated by nomic-embed-text to inspect semantic candidate grounding chunks.
          </p>
        </div>
        <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-zinc-900 border border-zinc-800 text-zinc-400">
          Model: nomic-embed-text
        </span>
      </div>

      <form onSubmit={handleSearch} className="flex gap-2">
        <div className="relative flex-1">
          <Search className="w-4 h-4 text-zinc-500 absolute left-3 top-2.5" />
          <input
            type="text"
            placeholder="Search candidate vector store (e.g. 'FastAPI async microservices')..."
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            className="w-full bg-zinc-900 border border-zinc-800 rounded pl-9 pr-3 py-2 text-xs text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-600 font-mono"
          />
        </div>
        <button type="submit" disabled={isSearching} className="min-button min-button-primary text-xs">
          <Cpu className="w-3.5 h-3.5" /> {isSearching ? "Embedding..." : "Vector Search"}
        </button>
      </form>

      <div className="space-y-2">
        {results.map((res) => (
          <div key={res.id} className="min-card p-3 space-y-1 font-mono text-xs">
            <div className="flex items-center justify-between text-zinc-500 text-[10px]">
              <span>ID: {res.id}</span>
              <span className="text-emerald-400 font-bold">Similarity Score: {(res.score * 100).toFixed(1)}%</span>
            </div>
            <div className="text-zinc-200 leading-relaxed">{res.content}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
