version: 2

updates:
  # ===========================
  # Python (Backend)
  # ===========================
  - package-ecosystem: "pip"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"

    open-pull-requests-limit: 10

    labels:
      - dependencies
      - backend

    commit-message:
      prefix: "deps"

  # ===========================
  # Node (Frontend)
  # ===========================
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"

    open-pull-requests-limit: 10

    labels:
      - dependencies
      - frontend

    commit-message:
      prefix: "deps"

  # ===========================
  # GitHub Actions
  # ===========================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

    labels:
      - github-actions

    commit-message:
      prefix: "ci"