flowchart TB

Presentation[Presentation Layer]

Application[Application Layer]

Domain[Domain Layer]

Infrastructure[Infrastructure Layer]

Presentation --> Application

Application --> Domain

Infrastructure --> Domain