flowchart TB

Gateway

ResumeService

RAGService

AgentService

PromptService

EvaluationService

NotificationService

Gateway --> ResumeService

Gateway --> RAGService

Gateway --> AgentService

Gateway --> PromptService

Gateway --> EvaluationService

Gateway --> NotificationService